version: '3'

services:
  pg:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ckb
      POSTGRES_PASSWORD: nervos
      POSTGRES_DB: explorer
    ports:
      - 5432:5432

    volumes:
      - ./data/pg:/var/lib/postgresql/data
  redis:
    image: redis:bullseye
    user: redis:redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  worker:
    &rails
    build: .
    entrypoint: foreman run
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://ckb:nervos@pg/explorer
      REDIS_URL: redis://redis
    depends_on:
      - redis
      - pg
    command: worker
  blocksyncer:
    <<: *rails
    command: blocksyncer
  web:
    <<: *rails
    command: web
    ports:
      - 3000:3000
