default: &default
  adapter: postgresql
  encoding: unicode
    #  host: 172.19.0.2
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  username: postgres
  password: 88888888
  reconnect: true
  port: 5432

development:
  <<: *default
  database: ckb_explorer_blank

test:
  <<: *default
  database: ckb_explorer_test
production:
  <<: *default
  database: ckb_explorer_blank

