name: Deploy to testnet

on: 
  push:
    branches:
      - testnet
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker_build.outputs.image }}
    steps:
      - name: Build and push
        id: docker_build
        uses: ./.github/workflows/build.yml 
        with:
        secrets: inherit
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workload: [ckb-explorer-api, ckb-explorer-syncer, ckb-explorer-worker]
    steps:
      - uses: ./.github/workflows/update-image.yml 
        with:
          k8s-namespace: testnet
          k8s-workload: ${{ matrix.workload }}
          image: ${{ needs.build.outputs.image }}
          api-url: ${{ secrets.KUBOARD_API_URL }}
          username: ${{ secrets.KUBOARD_USERNAME }}
          access-key: ${{ secrets.KUBOARD_ACCESS_KEY}}
      - uses: ./.github/workflows/restart-workload.yml 
        with: 
          k8s-namespace: testnet
          k8s-workload: ${{ matrix.workload }}
          api-url: ${{ secrets.KUBOARD_API_URL }}
          username: ${{ secrets.KUBOARD_USERNAME }}
          access-key: ${{ secrets.KUBOARD_ACCESS_KEY}}          

